language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

notifications:
  email:
    - xademax@gmail.com
  on_success: change
  on_failure: always
